### PR TITLE
halium 9 recovery with UBports logo and winking Yumi

### PR DESCRIPTION
**Pull request by luksus42**
Just switched some images and made Yumi wink randomly for now.
(is it possible not to merge it, but to create a new branch from it?)

### CODE REVIEW

**Comment by luksus42** [comment]
@UniversalSuperBox @Flohack74 : fyi

**Comment by Flohack74** [comment]
Ok seems we are getting there. I will try to get it working on one of my devices :)

**Comment by mariogrip** [comment]
@luksus42 is this ready? Why would you not want to merge? 

I would recommend doing a git amend to remove the need for 2 commits.

Example, do this from this branch with no other changes in it, this will remove the last commit and include the change in the first one:
```
git reset --soft HEAD^ # Removes the commit but keeps the changes staged
git commit --amend --no-edit # Includes the staged changes into your current commit (this will be your first in this case)
```
and then git force push it.

**Comment by luksus42** [comment]
@mariogrip Oh, I did not know, that this is waiting for me to do something.
I thought, one of you just needs to merge it.

Edit:
Ah, I see, I asked for a new branch. I don't know anymore, why I did this.
Perhaps because it is ubports specific and not "halium generic".

**Comment by Flohack74** [comment]
@mariogrip it seems to be uncritical, however I wanted to test this on the Oneplus 5 - unfortunately we are blocked by some oddities but I will take a dive today eve with @Vince1171 - you might want to join us.

**Review by Flohack74 — APPROVED** [review]

**Comment by Flohack74** [comment]
grafik
Thx so much @luksus42 !!!

**Pull request merged**
