### PR TITLE
system-image-upgrader: Fix reset to factory defaults

### PR DESCRIPTION
**Pull request by Flohack74**
See https://github.com/ubports/android_bootable_recovery/pull/14

### CODE REVIEW

**Comment by fredldotme** [comment]
I'm not sure we should support something other than system_root installations with Halium 9.0+, the devices have large enough system partitions now, even on A/B devices.

**Comment by fredldotme** [comment]
Also, this change wouldn't trigger on Halium 9.0 anyway as the Android portion is called `android-rootfs.img` now.

**Comment by Flohack74** [comment]
Ok sounds like a plan. But at least for development with halium-install this would still be nice, then you can verify reset to factory defaults before everything is properly installed. OR we finally learn halium-install to install in system partition :)

**Comment by Flohack74** [comment]
Closed in favour of #5

**Pull request closed without merging**
